
```{r}
sessionInfo()
```


```{r}
?install.packages()
```


```{r}
#| eval: FALSE
update.packages()
```


```{r}
install.packages("dplyr")
```


```{r}
?library()
```


```{r}
library(dplyr)
```


```{r}
install.packages("BiocManager")
```

```{r}
library(BiocManager)
```


```{r}
?install()
```


```{r}
install("PeacoQC")
```


```{r}
library(PeacoQC)
```

```{r}
sessionInfo()
```


```{r}
installed.packages()
```


```{r}
install.packages("remotes")
```


```{r}

```


```{r}
library(remotes)
```


```{r}
install_github("hally166/flowSpectrum")
```


```{r}
install.packages("purrr")
```


```{r}
force = TRUE
install("flowCore", force = TRUE)
```


```{r}
force = TRUE
```


```{r}
install.packages("stringr")
```


```{r}
install("ggcyto")
```


```{r}
install.packages("tidyr")
```


```{r}
install("openCyto")
```


```{r}
install("FlowSOM")
```


```{r}
install.packages("xml2")
```


```{r}
install_github("saeyslab/CytoNorm")
```


```{r}
install.packages("lubridate")
```


```{r}
install.packages("httr2")
```


```{r}
install("flowGate")
```


```{r}
install.packages("devtools")
```


```{r}
install("plotly")
```


```{r}
install_github("biosurf/cyCombine")
```


```{r}
install("CytoML")
```


```{r}
install.packages("Rtsne")
```
